version: '3'

services:
  backend:
    build:
      context: ..
      dockerfile: docker/backend.dockerfile
    ports:
      - "3000:3000"
    volumes:
      - app-data:/app/data

  frontend:
    build:
      context: ..
      dockerfile: docker/frontend.dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  app-data:
